### ISSUE TITLE
Finding hits

### ISSUE THREAD

**Issue by SaraSiwiecki** [SaraSiwiecki/finalproject#1]
I was generally having some issues using BLAST and being able to locate a bait sequence that will produce results where I have at least one decent hit from many ctenophore, porifera, and choanoflagellate species. I've played around with the BLAST parameters a bit and it seems that I've found some parameters that work best. However, I spent a long time trying to find good bait sequences and have only been able to find a couple, so I changed the project a bit to be able to just compare trees made from different collagen IV alpha chain sequences to identify any patterns in the presence or absence of alpha chains since just that appears that it's going to take a while. 

I also wasn't sure if I should try using protein BLAST instead, but I didn't really find substantial hits with that either.

**Comment by lemellenthin** [comment]
Hey hey is this still an issue you are dealing with? Last time we talked I think we figured out some solutions but I just want to make sure!

**Comment by SaraSiwiecki** [comment]
Yes this is still somewhat of an issue! I am just unsure of if I should continue filtering through to find as many sequences as I can, or if I should try to see if protein BLAST works better...

**Comment by caseywdunn** [comment]
I would definitely focus on preotein sequences and use blastp - nucleotide sequences will be very saturated in the second and third codon positions.
